name: Deploy Eleventy site to GitHub Pages

on:
  push:
    branches:
      - main  # or master if your default branch is master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: List files for debugging
        run: ls -R src/_posts/data

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21'

      - name: Enable Corepack
        run: corepack enable

      - name: Prepare pnpm
        run: corepack prepare pnpm@8.15.6 --activate

      - name: Install dependencies
        run: pnpm install

      - name: Build the site
        run: pnpm run build
      
      - name: Create .nojekyll file
        run: echo "" > ./_site/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site  # Adjust this if your build output directory is different